---
- name: create vm 
  hosts: localhost
  become: false
  gather_facts: false
  
  vars_files:
    - vars.yml
  
  tasks:
    - name: create folder
      community.vmware.vcenter_folder:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: "{{ vcenter_validate_certs }}"
        datacenter: "{{ vcenter_datacenter }}"
        folder_name: "{{ vcenter_destination_folder }}"
        folder_type: vm
        state: present
    - name: create VM
      community.vmware.vmware_guest:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: "{{ vcenter_validate_certs }}"
        datacenter: "{{ vcenter_datacenter }}"
        template: "{{ vm_template }}"
        name: "{{ vm_name }}"
        folder: "{{ vcenter_destination_folder }}"
        state: "{{ vm_state }}"
        guest_id: "{{ vm_guestid }}"
        cluster: "{{ vcenter_cluster }}"
        disk:
          - size_gb: "{{ vm_disk_gb }}"
            type: "{{ vm_disk_type }}"
            datastore: "{{ vm_disk_datastore }}"
        hardware:
          memory_mb: "{{ vm_hw_ram_mb }}"
          num_cpus: "{{ vm_hw_cpu_n }}"
          scsi: "{{ vm_hw_scsi }}"
          hotadd_cpu: "{{ hot_add_cpu | default('True') }}"
          hotadd_memory: "{{ hot_add_memory | default('True') }}"
        network:
          - name: "{{ vm_net_name }}"
            start_connected: yes
            device_type: "{{ vm_net_type }}"
            type: static
            ip: "{{ vm_ip }}"
            netmask: "{{ vm_net_mask }}"
            gateway: "{{ vm_net_gw }}"
            dns_servers: "{{ vm_net_dns }}"