---
- name: Start the repair on Cassandra cluster
  hosts: cassandra
  serial: 1
  become: yes

  tasks:
    - name: Start the repair on the first Cassandra node
      register: output
      shell: |
        cd /opt/apps/cassandra
        . /opt/apps/cassandra/.bash_profile
        nohup nodetool -u k2view -pw Q1w2e3r4t5 repair --full >> /opt/apps/cassandra/repair.log 2>&1 &
      become_user: cassandra

    - name: Debug output
      debug:
        var: output.stdout_lines
